providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "gcc", "libxml2", "libxslt"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app.main:app -k uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:$PORT --timeout 120"
